#!/bin/bash -l
#SBATCH --job-name="NeRF_job_Gopher"
#SBATCH --ntasks=128
#SBATCH --output=Nerf.out
#SBATCH --error=Nerf.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=coffe176@umn.edu
#SBATCH --time=24:00:00
#SBATCH -p a100-4
#SBATCH --gres=gpu:a100:1

module load python3
pip3 install h5py
pip3 install typing-extensions
pip3 install wheel
pip3 install -r requirements.txt
module load gcc/9.2.0
pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
python run_nerf.py --config configs/DragonPics.txt
